### ISSUE TITLE
Enhancement in publication section

### ISSUE THREAD

**Issue by khawar512** [ravijo/Awesome-CV#1]
I would like to give one suggestion related to the publication section is that "Please add Impact Factor" Where we can write Journal Impact factor or H-Index. The impact factor and journal/conference name should be bold so it will be helpful for the reader. I am requesting you to please do it as soon as possible

**Comment by khawar512** [comment]
Still waiting

**Comment by ravijo** [comment]
@khawar512

Apologies for the delay in responding.

Thanks for creating this issue about adding the impact factor. Before I begin on implementation, I have the following points for discussion:
* So far I haven't seen anybody in the latex community writing impact factor or H-Index. In fact, I am unaware if there exists a field in latex bibliography management to mention impact factor or H-Index. Please let me know more.
* In your issue, you mentioned changing the style of journal/conference name. More specifically you requested to write the journal/conference name in bold letters. Please see the current formatting [here](https://github.com/ravijo/Awesome-CV/blob/master/examples/cv/cv-0.png). At present, the journal/conference name is written in italic letters in light gray color. If we write journal/conference names in bold letters, then almost all of the content will be in bold letters, which will certainly look odd.

**Comment by khawar512** [comment]
@ravijo 
No problem. I know you are busy because of your research work.

Currently, there is no field in the bibliography management to mention impact factor or H-Index. You are right, I just want to mention IF and H-Index in C.V especially in the publication section. So everyone knows that this journal has an impact factor.

At this moment, the journal name is present with a gray color which is not highlighted that much. Is it possible? If we just change light gray to black color to make it more visible.

**Comment by ravijo** [comment]
@khawar512 

Thanks for your response.

> Currently, there is no field in the bibliography management to mention impact factor or H-Index. You are right, I just want to mention IF and H-Index in C.V especially in the publication section. So everyone knows that this journal has an impact factor.

I understand. To do so, you can define your own bib field and bib macro. Then you have to modify the bibliography driver for the article class because Journals are mentioned in the article entry.
 
> At this moment, the journal name is present with a gray color which is not highlighted that much. Is it possible? If we just change light gray to black color to make it more visible.

You can change the color easily by editing [awesome-cv.cls#L811](https://github.com/ravijo/Awesome-CV/blob/95b48f439eebe6f86e868b7f74714cbee4de2f89/awesome-cv.cls#L811). However, I am worried about the overall look and feel of the page. For example, gray color is used frequently as you might have noticed already. Please keep in mind that changing to dark may not produce a perfect-looking result.

Cheers!

**Comment by ravijo** [comment]
Closing this issue due to no further activity observed.
